# Generated by Django 4.2.4 on 2024-12-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0002_carrera_curso_facultad_profesor_matricula_materia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Facultad',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
