# Generated by Django 4.2.4 on 2024-12-08 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0004_facultad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.IntegerField()),
                ('modalidad', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.facultad')),
            ],
        ),
    ]
