# Generated by Django 4.2.4 on 2024-12-08 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0006_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('semestre', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=100)),
                ('aula', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.profesor')),
            ],
        ),
    ]
