# Generated by Django 4.2.4 on 2024-12-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Matriculas', '0007_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('periodo', models.CharField(max_length=50)),
                ('observaciones', models.TextField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Matriculas.estudiante')),
            ],
        ),
    ]
